### ISSUE TITLE
express route and simple chat with socket.io please

### ISSUE THREAD

**Issue by dhemitus** [clemos/haxe-js-kit#138]
i want to create restful api with mysql and express and simple chat room with socket.io is there any example for that? because i'm struggling using Router and Route.

thank you

**Comment by clemos** [comment]
There is a sample Express app on @matthijskamstra's excellent tutorials
http://matthijskamstra.github.io/haxenode/05website/exampleAdvanced.html
For SocketIo + Express, there is this sample : 
https://github.com/clemos/haxe-js-kit/blob/develop/test/SocketIoTest.hx
Mix the two and you should be able to achieve what you want :)

**Comment by dhemitus** [comment]
so using Router and Route just simply like this:
`app.get('/api/users', function(req, res) {
    var username = req.param('username');
    res.send('username: ' + username );
});`
or like this:
`app.put('/api/users', function(req, res) {
    var username = req.param('username');
    res.send('username: ' + username );
});`

is that correct?

**Comment by MatthijsKamstra** [comment]
socket example as well: http://matthijskamstra.github.io/haxenode/12socket/example.html

**Comment by MatthijsKamstra** [comment]
guess this can be closed ?

**Comment by clemos** [comment]
Yes, let's
