### ISSUE TITLE
Using Map<String,Int> with Mongoose

### ISSUE THREAD

**Issue by Tavrox** [clemos/haxe-js-kit#156]
Hello there!

I'm doing a Youtube Scraper and need to search through tags.
I tried to do use this typedef for a mongoose stored data

"
typedef ChannelStatsData = 
{
	linkedChannelID:String,
	tags:Map<String, Int>,
	averageByVideo :
	{
		likes:Float,
		dislikes:Float,
		comments:Float,
		views:Float	
	},
	best:
	{
		like:Float,
		dislike:Float,
		comments:Float,
		views:Float
	}
}
"

But it seems that Mongoose doesn't like the tags:Map<String,Int>, part.
Is it a problem of the lib or I should do a workaround? thx!

**Comment by clemos** [comment]
Hi,
Indeed, storing a haxe `Map` directly will likely fail, as Map is not a simple object.
I think you should store it in Mongoose as `haxe.DynamicAccess<Int>` (or just `Dynamic<Int>`, which both represent a simple object), and probably just use it like that (DynamicAccess is pretty similar to Map).
If you really want the field to be converted from / to an actual Map, you should probably either look into Mongoose documentation to know how / where to do that during serialization / deserialization (sorry, I don't recall where :\), or handle that in your own code.

**Comment by Tavrox** [comment]
Okay thanks :)
