### ISSUE TITLE
[Express] res.sendfile() is now res.sendFile()

### ISSUE THREAD

**Issue by rb1147x** [clemos/haxe-js-kit#158]
I've just started playing around with Haxe/Node/Express and noticed that the Express api shows the function sendfile() has been updated to sendFile() (capital F).

https://expressjs.com/en/4x/api.html#res.sendFile

**Comment by clemos** [comment]
Thanks for the insight, PR welcome :)

**Comment by MatthijsKamstra** [comment]
Hi @clemos , you can close this one

**Comment by clemos** [comment]
Thx :)
