### ISSUE TITLE
update with $pull

### ISSUE THREAD

**Issue by varadig** [clemos/haxe-js-kit#166]
How can I use the pull query for mongoose like this:
```
collection.update(
  { _id: id },
  { $pull: { 'contact.phone': { number: '+1786543589455' } } }
);
```

The haxe compiller failed with this error:
_Field names starting with a dollar are not allowed_

**Comment by clemos** [comment]
I think you can : 
```haxe
collection.update(
  { _id: id },
  { "$pull": { 'contact.phone': { number: '+1786543589455' } } }
);
```
see https://try.haxe.org/#59F26

**Comment by clemos** [comment]
ie use `"` :D

**Comment by varadig** [comment]
yes, it's working, but I use IntelliJ with FileWatcher, but the editor gave me error for this "$pull"
![screen shot 2017-08-07 at 16 43 53](https://user-images.githubusercontent.com/6317148/29031821-c0c317f2-7b8f-11e7-88e1-902e0cc6c702.png)

**Comment by clemos** [comment]
Well, I guess you should report that to the haxe-intellij team, then :)

**Comment by varadig** [comment]
yes ;) thanks

**Comment by varadig** [comment]
I found the "solution":

```
        var update:Dynamic = {};
        Reflect.setField(update,"$push",{likes:{_id:id}});
        this.userManager.update({_id:context.currentUserID},update, function(err, user) {});
```

**Comment by varadig** [comment]
https://github.com/HaxeFoundation/intellij-haxe/issues/662#issuecomment-326082302

**Comment by varadig** [comment]
#https://github.com/HaxeFoundation/intellij-haxe/issues/662#issuecomment-326082302

**Comment by varadig** [comment]
https://github.com/HaxeFoundation/intellij-haxe/issues/662#issuecomment-326082302
