### ISSUE TITLE
Generate ObjectID before create

### ISSUE THREAD

**Issue by varadig** [clemos/haxe-js-kit#167]
How can I (if its possible) create uniq ObjectID before execute create.
I wanted to create folder by the id of the document, for media contents.

in mongoose:
```
var mongoose = require('mongoose');
var id = mongoose.Types.ObjectId();
```

thanks

**Comment by clemos** [comment]
In haxe you can do : 
```haxe
import js.npm.mongoose.types.ObjectId;
// ... then
var id = new ObjectId();
```

Best,
Clément

**Comment by varadig** [comment]
There is no js.npm.mongoose.types.ObjectId, just js.npm.mongoose.schema.types.ObjectId
but the js.npm.mongoose.schema.types.ObjectId need path and options, and I cannot generate _id.

**Comment by clemos** [comment]
I think the `ObjectId` in `schema` is for creating schema fields, not ObjectId instances.
I think what you want is `js.npm.mongoose.types.ObjectId` which is actually here https://github.com/clemos/haxe-js-kit/blob/develop/js/npm/mongoose/types/ObjectId.hx

**Comment by varadig** [comment]
Thanks.
remove js-kit and reinstall  from github, and there is types  package with ObjectID class
