### ISSUE TITLE
SubDocument with nested schema

### ISSUE THREAD

**Issue by varadig** [clemos/haxe-js-kit#168]
How can I create nested schema/subdoc like this?:
http://mongoosejs.com/docs/subdocs.html

thanks

**Comment by clemos** [comment]
mm, can you elaborate ? what have you tried ?

**Comment by varadig** [comment]
I need to create Foundation collection, with nested Event collections.
So I have to dynamical create Foundations, and after also create Events under Foundations.

Sorry for my english, I hope you understand what how I mean

**Comment by clemos** [comment]
Please post the code you used to declare your current model / schemas, this will help.

**Comment by varadig** [comment]
**Event.hx:**
```
package model.scema;

typedef EventData =
{
title:String,
sup_org_name:String,
city:String,
address:String,
date:String,
time:String,
foundation_description:String,
event_description:String,
logo_link:String,
?joins:Array<EventAction>
}

typedef EventAction =
{
_id:String,
ts:Float
}
class EventManager extends js.npm.mongoose.macro.Manager<EventData, Event> {}

@:schemaOptions({
    autoIndex: true
})

class Event extends js.npm.mongoose.macro.Model<EventData> {}
```

**Foundation.hx:**

```
package model.scema.foundation;
import js.npm.mongoose.macro.*;
typedef FoundationData = {
name:String,
events:Array<Event>
}
class FoundationManager extends Manager<FoundationData, Foundation> {}
class Foundation extends Model<FoundationData> {}

```

**Comment by varadig** [comment]
But maybe this is solve, what I want:

```
package model.scema.foundation;
import js.npm.mongoose.macro.*;
typedef FoundationData = {
name:String,
events:Array<FoundationEvent>
}

typedef FoundationEvent = {
title:String,
sup_org_name:String,
city:String,
address:String,
date:String,
time:String,
foundation_description:String,
event_description:String,
logo_link:String,
?joins:Array<EventAction>
}
typedef EventAction =
{
_id:String,
ts:Float
}
class FoundationManager extends Manager<FoundationData, Foundation> {}
class Foundation extends Model<FoundationData> {}

```

**Comment by clemos** [comment]
This probably won't work as is.

First thing you need to do is generate a schema out of `FoundationEvent` (if I were you, I would rename it `FoundationEventData` and have a `FoundationEvent extends Model<FoundationEventData> { }`. The Schema is accessible via `FoundationEvent.Schema`.

Then you will have to set the `events` field of your `Foundation.Schema` an `[FoundationEvent.Schema]` (currently the macro will probably generate a `[Mixed]` field).

I think you can do this manually like that : 
```
Foundation.Schema.path("events", [FoundationEvent.Schema]);
```

Or better yet, you could maybe modify the macro somewhere around [here](https://github.com/clemos/haxe-js-kit/blob/develop/util/Mongoose.hx#L515-L527) to detect `js.npm.mongoose.Schema` type, and return the right Schema type (not sure how to do it right...)

Let me know if any of these options work :|

**Comment by clemos** [comment]
Can we assume the schema type of a `Model` should always be its `Schema` ? 
Otherwise we should maybe add a new metadata like `events: Array<@subdocument FoundationEvent>` to distinguish "embedded" documents from "linked" documents ??

**Comment by clemos** [comment]
There seem to be a `:ref` metadata [here](https://github.com/clemos/haxe-js-kit/blob/develop/util/Mongoose.hx#L348) but I'm not sure what it's supposed to do :S

**Comment by varadig** [comment]
Sorry for the late reply, but I was very busy.

So I wanted to try your first suggestion.

Now the foundation class is looks likt this:

```
package model.scema.foundation;
import js.npm.mongoose.macro.*;

typedef FoundationData = {
name:String,
color_code:String,
description:String,
events:Array<FoundationEvent>,
metatags:Array<String>
}

typedef FoundationEventData = {
title:String,
city:String,
address:String,
date:String,
time:String,
description:String,
metatags:Array<String>,
featured_image_link:String,
?userJoined:Bool,
?joins:Array<FoundationEventActionData>
}


typedef FoundationEventActionData =
{
_id:String,
ts:Float,
region:String,
division:String,
file_name:String
}

class FoundationEvent extends Model<FoundationEventData> { }
class FoundationManager extends Manager<FoundationData, Foundation> {}
class Foundation extends Model<FoundationData> {}
```


the only thing I dont know, how can I found and update the event  in the FoundationManager by the event._id?

**Comment by clemos** [comment]
> the only thing I dont know, how can I found and update the event in the FoundationManager by the event._id?

I'm sorry, I have very few experience with subdocuments, so I'm afraid I don't know either :\
This js-kit lib probably lacks further support for subdocuments (for instance, your model `events` won't be typedef as a `MongooseArray`)
I guess you should try and do what you need in native JS to understand how it works, and then try to inject it in your Haxe code (via `untyped __js__` maybe).
Looking at the generated source will also probably give you hints as to how to implement it in Haxe.

**Comment by varadig** [comment]
thanks ;)
