### ISSUE TITLE
haxe 4 mongoose issue

### ISSUE THREAD

**Issue by varadig** [clemos/haxe-js-kit#183]
Whats wrong with my code:

EquipmentModel:
```
package model.database.schema.model;
import model.database.schema.data.EquipmentData;


@:schemaOptions({autoIndex: true})
class EquipmentModel extends js.npm.mongoose.macro.Model<EquipmentData> {}

```

![Screenshot 2019-12-18 10 55 53](https://user-images.githubusercontent.com/6317148/71075883-17b00500-2185-11ea-9c0b-efaf6a3d30e1.png)

EquipmentData:

```
package model.database.schema.data;

typedef EquipmentData = {
	name:String,
	description:String,
	price:Float
}
```

EquipmentManager:
```

package model.database.schema.manager;
import js.npm.mongoose.macro.Manager;
import model.database.schema.model.EquipmentModel;
import model.database.schema.data.EquipmentData;
class EquipmentManager extends Manager<EquipmentData, EquipmentModel> {}

```

the error:

`src/model/database/schema/model/EquipmentModel.hx:6: character 1 : Variable requires type-hint or initialization`

with haxe 3 is working well, but I need to use version 4x

**Comment by varadig** [comment]
There is no clue where I need to find a variable in the mongoose script to initialize or typehint
@clemos , can you explain me where I need to find/change your code to haxe4 compatible?
thanks

**Comment by clemos** [comment]
Hi @varadig 
The `js.npm.mongoose.macro` package apprently needs to be upgraded to Haxe 4;
I don't think I can do this anytime soon.

**Comment by clemos** [comment]
One of the generated `FVar`s here probably need "type-hint or initialization" https://github.com/clemos/haxe-js-kit/blob/develop/util/Mongoose.hx

**Comment by varadig** [comment]
Thank You @clemos , I will check and try to upgrade to hx4
