### ISSUE TITLE
Mongoose document save() has no argument

### ISSUE THREAD

**Issue by JbIPS** [clemos/haxe-js-kit#20]
Hi,

I'm trying to save a mongoose document with its save method. I saw in `js.npm.mongoose.Model.hx`:
```

@:native("Model")
extern class TModel<T>
extends Document<T>
implements npm.Package.RequireNamespace<"mongoose","*"> 
{
...
	public function save( fn : Callback<TModel<T>> ) : Void;
...
}
```
So I tried: 
```
class MyModel extends Model<MyModelData>{}
class MyModelDOA{
     public function clone(mod: MyModel, callback: Callback<MyModel>):Void
	{
		mod.save(callback);
	}
}
```
But I get `Function 'save' requires no arguments`. The weird thing is that I can use any function on the model and it didn't trigger any compilation errors (I tried `mod.hjdzjhuhef()` and it compiled), like it's a Dynamic.
Is there an interference with another save function ?

**Comment by clemos** [comment]
Closing it, as I believe it's been fixed
