### ISSUE TITLE
Sample apps

### ISSUE THREAD

**Issue by fullofcaffeine** [clemos/haxe-js-kit#23]
Just found this repo, and as someone currently using Haxe for js work, this is will certainly be useful. Do you have any samples apps available, i.e for expressjs? It'd be great to see how the same app would look written in Haxe vs vanilla Javascript, to compare the cost/benefits of using either languages.

Keep up the great work!

**Comment by clemos** [comment]
There is a very minimal example for Express here : 
https://github.com/clemos/haxe-js-kit/blob/master/test/ExpressTest.hx
