### ISSUE TITLE
Cannot construct a Mongoose model with an object

### ISSUE THREAD

**Issue by ciscoheat** [clemos/haxe-js-kit#25]
Check out this gist: https://gist.github.com/ciscoheat/2ea2034a239024c89547

When using `Date.now()` in the call to construct, the javascript output isn't compiled to `new attractions({...})`, but when using a variable it works.

Thanks for the great mongoose API you've made, it really simplifies things.

**Comment by clemos** [comment]
It seems it's a bug in the compiler itself.
I'll check and report it ;)
Thanks for the report !

**Comment by clemos** [comment]
I reported it here : 
https://github.com/HaxeFoundation/haxe/issues/3748
It seems expressions such as `Date.now()` can't be inlined, which may be a feature.
So in the meantime, I've removed `inline` from this `construct` method

**Comment by clemos** [comment]
Mh I actually reverted the so called 'fix', as obviously non inlined methods are not generated for an extern :\

**Comment by clemos** [comment]
It's actually fixed in latest haxe version (dev)
Thanks for reporting ;)
