### ISSUE TITLE
Using @async with Mongoose .find()

### ISSUE THREAD

**Issue by theRemix** [clemos/haxe-js-kit#34]
how do you use @async to get all documents with mongoose?

this in the normal callback way that works

````
post.find().exec(function( err:String, docs:Array<Post> ){
  res.render('index', { posts : docs });
});

````
-----

if i do this, i get a compile time error
using Haxe version 3.1.3 [stable]

````
var query = post.find();
var err,docs = @async query.exec();
if(err != null) trace(err);
res.render('index', { posts : docs });

// error
Local variable err used without being initialized
````

-----

this compiles, yet does not give me an array of documents like i expected

````
var err,docs = @async query.exec();
res.render('index', { posts : docs });
````
tracing `docs` shows this

````
{
	domain : null, 
	_events : {

	}, 
	_maxListeners : 10, 
	emitted : {

	}, 
	ended : false
}
````

-----

i think i'm using the model find and query exec incorrectly, can you show me an example please?

**Comment by clemos** [comment]
There's an example here : https://github.com/clemos/haxe-js-kit/blob/master/test/MongooseTest.hx
I believe your issue is that your containing class doesn't implement `util.Async`.

**Comment by clemos** [comment]
Feel free to reopen if needed
