### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by clemos** [clemos/haxe-js-kit#35]
Hi contributors !
@cloudshift @as3boyan @async-cl @dionjwa @Peekmo @JbIPS @andyli @sledorze @labe-me @nesbox @jasononeil @ccapndave
I'd like to licence haxe-js-kit code, as @underscorediscovery asked me, so people can use it freely.
I think MIT would be fine, but since you contributed one way or another to this project, I thought I'd let you know.
Let me know if you have any problem with that; otherwise I'll just add the licence by the end of the week.

**Comment by JbIPS** [comment]
I always use MIT, no problem with me ;-)

**Comment by sledorze** [comment]
No problem at all :)
Le 23 févr. 2015 16:49, "Clément Charmet" <notifications@github.com> a
écrit :

**Comment by as3boyan** [comment]
no problem, bro, MIT

**Comment by jasononeil** [comment]
MIT FTW :)

It's fine with me.

**Comment by dionjwa** [comment]
No problem.

**Comment by ccapndave** [comment]
Sure :)

**Comment by labe-me** [comment]
No problem !

**Comment by clemos** [comment]
Thank you all :)
