### ISSUE TITLE
Deprecated Middleware file?

### ISSUE THREAD

**Issue by ciscoheat** [clemos/haxe-js-kit#37]
The file https://github.com/clemos/haxe-js-kit/blob/dev/js/npm/connect/support/Middleware.hx won't compile as it is now (missing two imports), but it seems to be replaceable with https://github.com/clemos/haxe-js-kit/blob/dev/js/npm/express/Middleware.hx anyway. Remove it?

**Comment by clemos** [comment]
Yeah I don't know what to do with Connect, now that Express is completely independant.
This file is part of the Connect extern I made for Express support. 
I'm thinking about removing Connect entirely, now, in favor of Express, which I feel is better.
What do you think ?

**Comment by ciscoheat** [comment]
I have the same feeling. If you think it's too much work to support both, remove Connect. It will hopefully lessen the confusion for newcomers as well.

**Comment by dionjwa** [comment]
+1 It would be great to merge this into master since it currently doesn't compile. +1 for removing Connect.

**Comment by clemos** [comment]
I think this is fixed, now (removed `connect`)
