### ISSUE TITLE
Express router has no method get

### ISSUE THREAD

**Issue by tiagolr** [clemos/haxe-js-kit#45]
Hi, only now i noticed there exists a `dev` branch and i switched to it to avoid rewriting new additions like Morgan like i did a couple of days ago.

I found i cannot use `Router.get()` while i can use `Router.all()` and Router.post()

I was using the following code to place routes on different folders.
```haxe
class App {
    static function main() {
        var port = 8000;
        var app = new Express();

       app.use('/', new Index().router);
       app.use('/users', new Users().router);
    }
}

class Index {
	public var router:Router;
	public function new() {
		router = new Router();
		router.all('/', function(req:Request, res:Response) {
			res.end("Index");
		});	
	}
}

class Users { .... } 
```

Now i have to replace `Router.get()` with `Router.all()`.

PS - If you know a better way to place routes on different folders let me know, i found this hacky way so far.

**Comment by clemos** [comment]
Still having this issue ?
Sorry for the delay :\
