### ISSUE TITLE
Trouble compiling 

### ISSUE THREAD

**Issue by Jean-FrancoisTrevien** [clemos/haxe-js-kit#60]
Hello,

I have tried to use your library, for this i have in my hxml file the path of a clone of your code.
and i use a simplified version of your express example ( just static entry)
But i have the following errors messages:

/home/systrans/haxemk/haxe-js-kit/npm/Package.hx:249: characters 7-40 : Duplicate type parameter name: Const
/home/systrans/haxemk/haxe-js-kit/npm/Package.hx:252: characters 7-49 : Duplicate type parameter name: Const

When i look at line 249 : 
extern interface Require<Const,Const> {}

And when i look at line 252 
extern interface RequireNamespace<Const,Const> {}

I have the same errors when i do:
haxe test.hxml 
in the haxe-js-kit directory

**Comment by clemos** [comment]
Can you confirm my commit fixes it ?
Also, what version of Haxe are you using ? I can't seem to reproduce this issue.

**Comment by Jean-FrancoisTrevien** [comment]
The problem is solved , the version avec haxe i use is 3.3.0.

Thanks a lot.

 

De : Clément Charmet [mailto:notifications@github.com] 
Envoyé : mercredi 19 août 2015 13:41
À : clemos/haxe-js-kit
Cc : Jean-FrancoisTrevien
Objet : Re: [haxe-js-kit] Trouble compiling (#60)

 

Can you confirm my commit fixes it ?
Also, what version of Haxe are you using ? I can't seem to reproduce this issue.

**Comment by ianharrigan** [comment]
I get something similar to this:

```
\lib/js-kit/git/atomshell/Package.hx:236: characters 31-36 : Duplicate type parameter name: Const
\lib/js-kit/git/atomshell/Package.hx:239: characters 40-45 : Duplicate type parameter name: Const
```

Any ideas? It seems to have only just started to happen, which is strange as i dont think ive updated anything

**Comment by clemos** [comment]
`atomshell.Package` seem to be outdated.
You update it with [this part](https://github.com/clemos/haxe-js-kit/blob/haxelib/npm/Package.hx#L251-L265) of the "main" `npm.Package`.
I think duplicating this class has obviously been a mistake, there is certainly a better way to handle this :\
