### ISSUE TITLE
extern for fs.readFile()

### ISSUE THREAD

**Issue by fullofcaffeine** [clemos/haxe-js-kit#61]
Hey guys,

I need to read some files from the filesystem from my Haxe nodejs app, but I just found out that externs for the `fs` module are not complete. There's only a `FSWatcher.hx` and a `Stats.hx` there. 

I'd like to add the extern for `fs.readFile()`, and also learn the pattern for adding others - I'm not sure how I should name the class, and also what is needed, since I see some macro magic is being used there (in the implements call). Could someone point me in the right direction - an example would be great! 

Thanks in advance!

**Comment by fullofcaffeine** [comment]
Nevermind, it just worked out of the box, must have looked in the wrong place!

**Comment by clemos** [comment]
For the record, most `fs` methods are in `js.node.Fs` ;)
