### ISSUE TITLE
Electron shell examples?

### ISSUE THREAD

**Issue by fullofcaffeine** [clemos/haxe-js-kit#62]
Wondering if the electron (atom-shell) externs are up to date? Any example of how to use it with Haxe?

Thanks!

**Comment by fullofcaffeine** [comment]
I managed to create a 'Hello World' electron app with Haxe without using externs. It works, but I'm using a lot of `untyped` there. Any suggestions on how to improve would be greatly appreciated!

https://github.com/fullofcaffeine/projectgtd/blob/master/src/haxe/App.hx

**Comment by clemos** [comment]
@as3boyan ?

**Comment by clemos** [comment]
I don't think they are up-to-date, since they're still `atom-shell` instead of `electron`.
Also, the `atomshell.Package` tooling probably needs some refactoring.

**Comment by fullofcaffeine** [comment]
@clemos Alright, fair enough, I'll be adding on a need to use basis.

**Comment by as3boyan** [comment]
Hmm I noticed this, his code looks like it is compatible, but it seems like they promote another way to use classes:

```cs
const electron = require('electron');
const app = electron.app;
```

I haven't used it for a while, can't find in documentation old way of doing this (like `require('app')`), don't know if it works
