### ISSUE TITLE
Model<T> vs TModel<T>?

### ISSUE THREAD

**Issue by kevinresol** [clemos/haxe-js-kit#69]
Not sure about the difference.... but I am guessing [these lines](https://github.com/clemos/haxe-js-kit/blob/master/js/npm/mongoose/Model.hx#L67-L69) should use `M` instead of `Model<T>`, just like `findOne`?

**Comment by clemos** [comment]
Yeah you're probably right.
Unfortunately I don't really work no nodejs/mongoose anymore, and don't have time to make the changes and test them properly.
So feel free to make a PR ;)

**Comment by clemos** [comment]
Is it completely fixed ?

**Comment by kevinresol** [comment]
yes, #70 fixes it

**Comment by clemos** [comment]
Thx

**Comment by kevinresol** [comment]
forgetting to merge? #70
