### ISSUE TITLE
exporting your project dependencies doesn't work anymore

### ISSUE THREAD

**Issue by MatthijsKamstra** [clemos/haxe-js-kit#74]
Hi Clemos, 

it looks like 
```
--macro npm.Package.export("package.json")
```
doesn't work anymore

**Edit**
perhaps something to do with my Haxe version: 3.2.0

**Comment by clemos** [comment]
Yeah there has been quite a lot of changes these past few weeks regarding how constants are handled, which brought :hankey: : 
https://github.com/clemos/haxe-js-kit/commits/master/npm/Package.hx
You may try to checkout one of these commits and let me know which one works for you...

**Comment by MatthijsKamstra** [comment]
None of them work: 

https://github.com/clemos/haxe-js-kit/commit/63b5ab3c6aa785006639452f8597c5c9f2b55779
will give
`/usr/lib/haxe/lib/js-kit/git/js/node/events/EventEmitter.hx:5: lines 5-21 : Constant value unexpected here` 

https://github.com/clemos/haxe-js-kit/commit/db8e9af9d11ec4f75da36eeebb6a77edbe057dbd
doesn't work but doesn't create errors

**Comment by clemos** [comment]
Ok I'll check it on my own asap.
Thanks for the tests :)
