### ISSUE TITLE
Mongoose Scheme: use underlying concrete type of abstracts

### ISSUE THREAD

**Issue by kevinresol** [clemos/haxe-js-kit#80]
Currently `Mixed` is used in the mongoose schema when the type is abstract. Is it possible to drill down to the concrete type of an abstract when creating the schema?

e.g. A field of type `abstract MyAb(String)` will become a String instead of Mixed in the schema

**Comment by clemos** [comment]
Yes, it could be nice.
You can try to replace https://github.com/clemos/haxe-js-kit/blob/master/util/Mongoose.hx#L536 with : 
```
typeToSchemaType( i.type , typeKey )
```
maybe that would be enough, though I'm not sure at all.

**Comment by kevinresol** [comment]
Ok let me check later and report.
