### ISSUE TITLE
Compile-time check of models ignored?

### ISSUE THREAD

**Issue by kevinresol** [clemos/haxe-js-kit#81]
Consider a model defined as follow:
```haxe
typedef StuffData = {
	test : String,
	foo : Int,
	?bar : {
		hello : String,
		world : Array<Dynamic>
	}
}

// declare the model
// the typedef fields will be "copied" to Stuff instance
@:schemaOptions({
    autoIndex: true
})
class Stuff extends Model<StuffData>{}
class StuffManager extends js.npm.mongoose.macro.Manager<StuffData,Stuff>{}
```

The following code will compile (but it should not):
```haxe
function test(stuff:Stuff) stuff.nonExistentField;
```

Any idea?

and `$type(stuff.nonExistentField)` gives me `Dynamic`

**Comment by clemos** [comment]
`Model` extends `Document` and thus is `dynamic`.
You can access a typed `StuffData` through `stuff._`.
At the time I didn't find a better way to do it while keeping the possibility to go macroless / untyped.

**Comment by kevinresol** [comment]
What is the reason behind extending `Document`?

**Comment by clemos** [comment]
This is made to support using mongoose in "untyped mode" (without macro models)

**Comment by kevinresol** [comment]
If that is the case, can we introduce a define the omit the "extend Dynamic" if use choose to use macro based model?

**Comment by clemos** [comment]
I don't know, there may be cases where you don't want to set that globally (for instance if you want only some models to be statically typed).

**Comment by kevinresol** [comment]
I am pretty sure that people like haxe because it is statically typed?
So what if we reverse it: the define will enable the "extend Dynamic", then this will be all-or-nothing (and by default it is "all" statically-typed)

**Comment by clemos** [comment]
You're probably right.
Actually, maybe it would be better to remove it entirely (no define)...
Once again, I don't really like defines...

**Comment by kevinresol** [comment]
Yay!
Is [this](https://github.com/clemos/haxe-js-kit/blob/master/js/npm/mongoose/Document.hx#L16) the only line to remove?

**Comment by clemos** [comment]
Yes, I guess.

**Comment by kevinresol** [comment]
ok I will test it for a while and submit a PR if it works fine.
