### ISSUE TITLE
haxe-js-kit and hxelectron and hxnodejs

### ISSUE THREAD

**Issue by MatthijsKamstra** [clemos/haxe-js-kit#84]
I am trying to combine a couple things in Electron.

Doesn't work... 
electron externs from js-kit are ... still called Atom

So I moved to hxelectron from Franco Ponticelli
and he uses `-lib hxnodejs`

But also want to use express (from js-kit)
you see where I am going...

it doesn't work.

if I copy `js.npm` files to a folder without the `js.node` 
I get:
```
lib/js/npm/express/Application.hx:3: characters 7-26 : Type not found : js.support.Callback
```
copied `js.support` folder
```
lib/js/npm/express/Middleware.hx:21: characters 2-7 : Type not found : util.CopyMethods
```
(magical stuff happening there)

and I remove `-lib hxnodejs`
and add `-lib js-kit`
```
lib/electron/main/BrowserWindow.hx:7: lines 7-26 : Type not found : Event
```

**Comment by MatthijsKamstra** [comment]
I can answer this question for you: https://github.com/clemos/haxe-js-kit/tree/develop (you are working on it)

**Comment by clemos** [comment]
Yeah, so now, on the `develop` branch, you should be able to make `hxnodejs` and `haxe-js-kit` together.
As for `atom`/`hxelectron`, you're probably right: we should either (1) drop support for it in favor of Franco's lib, or (2) update it. As I don't use it at all, I think I would rather (1)...

**Comment by MatthijsKamstra** [comment]
I would say drop it, I have worked with Franco's lib and it works great.
And I don't see Boyan updating it any time soon (he left the web-based editors for Intellij).

Any idea when you will push development to master? 
I will then update the documentation accordantly.

**Comment by clemos** [comment]
I can merge `develop` into `master` today: I didn't get any feedback, so I guess it's fine :p ...
What do you think ?

**Comment by MatthijsKamstra** [comment]
Go for it!

**Comment by clemos** [comment]
I merged all yesterday ;)
Sorry for the delay :p

**Comment by MatthijsKamstra** [comment]
and I updated it yesterday!
check out http://matthijskamstra.github.io/haxenode/

**Comment by clemos** [comment]
Awesome :)
