### ISSUE TITLE
Unexpected .

### ISSUE THREAD

**Issue by fullofcaffeine** [clemos/haxe-js-kit#86]
Getting this error with a test script:

![dvbxczf50g_vciuplblzruwa2djhpjya7_grhn_v7tw](https://cloud.githubusercontent.com/assets/81248/11832467/f9a1e2ce-a37d-11e5-908c-17c4071f9387.png)

Tried debugging `Middleware.hx` but couldn't find anything apparently wrong... any ideas? Using the `develop` branch.

I *can* compile the project but I can't get autocompletion.

Thanks!

**Comment by fullofcaffeine** [comment]
Is this error related to this, maybe: https://github.com/HaxeFoundation/haxe/issues/4535?

**Comment by fullofcaffeine** [comment]
I'm using Haxe 3.2.1, by the way.

**Comment by clemos** [comment]
You may want to try with Haxe nightly, as I believe it's a compiler issue.
Also, what editor are you using ?

**Comment by fullofcaffeine** [comment]
@clemos Vim with Vaxe.

I'll try nightly and let you know how it goes. Thanks!

**Comment by clemos** [comment]
I think I fixed it on `develop`, please confirm.
The workaround is quite strange: https://github.com/clemos/haxe-js-kit/commit/fffd4f551ca39372784adf3f7a0a2341b5cfad3c

**Comment by fullofcaffeine** [comment]
I'll pull today or tomorrow and confirm. So the workaround is basically changing the line order for the `extern` definition?

**Comment by fullofcaffeine** [comment]
Might worth pinging the Haxe core devs about this? I have no idea why this solve the issue either.

**Comment by clemos** [comment]
Yes, I'll try to narrow the issue and report it to the Haxe team when I have some time.

**Comment by fullofcaffeine** [comment]
I'm still having this error, `haxe-js-kit` just insalled from git with a clean Haxe 3.3.0 install.

**Comment by clemos** [comment]
You mean it's back ? Because I m pretty sure it was fixed ar some point...

**Comment by fullofcaffeine** [comment]
Hi Clément, looks like I had an older revision lying here, I cloned the latest revision from the repo and it works fine. Apologies for the noise!

**Comment by clemos** [comment]
No problem :)
